name: mobileriverpod
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  provider: ^6.1.2
  go_router: ^14.1.3
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.0
  mocktail: ^1.0.4
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.16
  build_runner: ^2.1.11
  
  

flutter:
  uses-material-design: true
